In [6]:
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [7]:
X,y = load_breast_cancer(return_X_y=True)

In [8]:
X_train , X_test, y_train, y_test = train_test_split(X,y , test_size=0.2)

In [ ]:
scaler = StandardScaler()
# use minmax scalr if you want it in range of 0-1


X_train_scaled = scaler.fit_transform(X_train)
# we dont do fit again coz we want to use same mean and variance not different ones
X_test_scaled = scaler.transform(X_test)

print("before transform", X_train)
print("after transform", X_train_scaled)

before transform [[1.742e+01 2.556e+01 1.145e+02 ... 1.099e-01 1.603e-01 6.818e-02]
 [2.018e+01 2.397e+01 1.437e+02 ... 2.508e-01 5.440e-01 9.964e-02]
 [1.613e+01 1.788e+01 1.070e+02 ... 1.864e-01 4.270e-01 1.233e-01]
 ...
 [1.218e+01 1.408e+01 7.725e+01 ... 1.852e-02 2.293e-01 6.037e-02]
 [1.245e+01 1.570e+01 8.257e+01 ... 1.741e-01 3.985e-01 1.244e-01]
 [1.775e+01 2.803e+01 1.173e+02 ... 1.970e-01 2.972e-01 9.075e-02]]
after transform [[ 0.94907513  1.44559389  0.946094   ... -0.05288673 -2.18450666
  -0.87643915]
 [ 1.73921184  1.08339938  2.16173305 ...  2.14241725  4.3111275
   0.87339772]
 [ 0.5797721  -0.3038739   0.63385795 ...  1.13902778  2.33044156
   2.18939073]
 ...
 [-0.55103951 -1.16949599 -0.6046784  ... -1.47664029 -1.01640982
  -1.31083921]
 [-0.47374353 -0.80046763 -0.38319896 ...  0.94738663  1.84796678
   2.25057384]
 [ 1.043548    2.00824824  1.06266213 ...  1.30418195  0.13306519
   0.37892697]]

In [12]:
knn  = KNeighborsClassifier()

knn.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [13]:
print(knn.score(X_test_scaled, y_test))

0.9736842105263158

In [2]:
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import OrdinalEncoder

In [16]:
data = fetch_openml("car", as_frame=True).frame

/Users/aayushmaanhooda/Desktop/codebase/january/f1/.venv/lib/python3.13/site-packages/sklearn/datasets/_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name car exist. Versions may be fundamentally different, returning version 2. Available versions:
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=991
- version 3, status: active
  url: https://www.openml.org/search?type=data&id=40975

  warn(warning_msg)

In [17]:
data

     buying  maint  doors persons lug_boot safety binaryClass
0     vhigh  vhigh      2       2    small    low           P
1     vhigh  vhigh      2       2    small    med           P
2     vhigh  vhigh      2       2    small   high           P
3     vhigh  vhigh      2       2      med    low           P
4     vhigh  vhigh      2       2      med    med           P
...     ...    ...    ...     ...      ...    ...         ...
1723    low    low  5more    more      med    med           N
1724    low    low  5more    more      med   high           N
1725    low    low  5more    more      big    low           P
1726    low    low  5more    more      big    med           N
1727    low    low  5more    more      big   high           N

[1728 rows x 7 columns]

In [19]:
columns_to_encode = ["lug_boot", "safety"]

encoder = OrdinalEncoder(
    categories=[
        ["small", "med", "big"],
        ["low", "med", "high"],
    ]
)
data[columns_to_encode] = encoder.fit_transform(data[columns_to_encode])
data

     buying  maint  doors persons  lug_boot  safety binaryClass
0     vhigh  vhigh      2       2       0.0     0.0           P
1     vhigh  vhigh      2       2       0.0     1.0           P
2     vhigh  vhigh      2       2       0.0     2.0           P
3     vhigh  vhigh      2       2       1.0     0.0           P
4     vhigh  vhigh      2       2       1.0     1.0           P
...     ...    ...    ...     ...       ...     ...         ...
1723    low    low  5more    more       1.0     1.0           N
1724    low    low  5more    more       1.0     2.0           N
1725    low    low  5more    more       2.0     0.0           P
1726    low    low  5more    more       2.0     1.0           N
1727    low    low  5more    more       2.0     2.0           N

[1728 rows x 7 columns]

In [20]:
encoder.inverse_transform(data[columns_to_encode])

array([['small', 'low'],
       ['small', 'med'],
       ['small', 'high'],
       ...,
       ['big', 'low'],
       ['big', 'med'],
       ['big', 'high']], shape=(1728, 2), dtype=object)

In [3]:
# one hot encoder turns multiple values for a individual features into multiple columns that can be 0 or 1
data = fetch_openml("adult", as_frame=True).frame

/Users/aayushmaanhooda/Desktop/codebase/january/f1/.venv/lib/python3.13/site-packages/sklearn/datasets/_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name adult exist. Versions may be fundamentally different, returning version 1. Available versions:
- version 1, status: active
  url: https://www.openml.org/search?type=data&id=179
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=1590

  warn(warning_msg)

In [4]:
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native-country,class
0,2,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,1,0,2,United-States,<=50K
1,3,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,0,United-States,<=50K
2,2,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,2,United-States,<=50K
3,3,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,2,United-States,<=50K
4,1,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,2,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,2,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,2,United-States,<=50K
48838,4,NaN,321403,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,2,United-States,<=50K
48839,2,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,3,United-States,<=50K
48840,2,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,2,0,2,United-States,<=50K
48841,1,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,3,United-States,>50K

In [5]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
import pandas as pd

encoder = OneHotEncoder(handle_unknown='ignore', sparse=False)

encoded_values = encoder.fit_transform(data[["occupation","race"]])