In [2]:
import fastf1
import os

In [ ]:
session = fastf1.get_session(2021, 1, "Q")
session.name
session.event
dir(session)

In [12]:
session.event

RoundNumber                                                   1
Country                                                 Bahrain
Location                                                 Sakhir
OfficialEventName    FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2021
EventDate                                   2021-03-28 00:00:00
EventName                                    Bahrain Grand Prix
EventFormat                                        conventional
Session1                                             Practice 1
Session1Date                          2021-03-26 14:30:00+03:00
Session1DateUtc                             2021-03-26 11:30:00
Session2                                             Practice 2
Session2Date                          2021-03-26 18:00:00+03:00
Session2DateUtc                             2021-03-26 15:00:00
Session3                                             Practice 3
Session3Date                          2021-03-27 15:00:00+03:00
Session3DateUtc                             2021-03-27 12:00:00
Session4                                             Qualifying
Session4Date                          2021-03-27 18:00:00+03:00
Session4DateUtc                             2021-03-27 15:00:00
Session5                                                   Race
Session5Date                          2021-03-28 18:00:00+03:00
Session5DateUtc                             2021-03-28 15:00:00
F1ApiSupport                                               True
Name: 1, dtype: object

In [16]:
session = fastf1.get_session(2025, "australia", "Race")
session.event["Session4"]

'Qualifying'

In [ ]:
schedule = fastf1.get_event_schedule(2026)
schedule

In [19]:
'''
You do not need to provide the exact event name. 
FastF1 will return the event (or session) that matches your provided name best. 
Even if you don’t specify the correct name chances are high that FastF1 will find the event you are looking for.
IT DOES FUZZY STRING MATCH
'''

session = fastf1.get_session(2025, "Australia", "Race")
session.load()
session.results

core           INFO 	Loading data for Australian Grand Prix - Race [v3.7.0]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '87'
core        WARNING 	Fixed incorrect tyre stint information for driver '30'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver 241: Position data is incomplete!
_api        WARNING 	Driver 242: Position data is incomplete!
_api        WARNING 	Driver 243: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core        WARNING 	Driver 4 completed the race distance 00:00.022000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '63', '12', '23', '18', '27', '16', '81', '44', '10', '22', '31', '87', '30', '5', '14', '55', '7', '6']

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
4,4,L NORRIS,NOR,norris,McLaren,FF8000,mclaren,Lando,Norris,Lando Norris,...,1.0,1,1.0,NaT,NaT,NaT,0 days 01:42:06.304000,Finished,25.0,57.0
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671C6,red_bull,Max,Verstappen,Max Verstappen,...,2.0,2,3.0,NaT,NaT,NaT,0 days 00:00:00.895000,Finished,18.0,57.0
63,63,G RUSSELL,RUS,russell,Mercedes,27F4D2,mercedes,George,Russell,George Russell,...,3.0,3,4.0,NaT,NaT,NaT,0 days 00:00:08.481000,Finished,15.0,57.0
12,12,A ANTONELLI,ANT,antonelli,Mercedes,27F4D2,mercedes,Andrea Kimi,Antonelli,Andrea Kimi Antonelli,...,4.0,4,16.0,NaT,NaT,NaT,0 days 00:00:10.135000,Finished,12.0,57.0
23,23,A ALBON,ALB,albon,Williams,64C4FF,williams,Alexander,Albon,Alexander Albon,...,5.0,5,6.0,NaT,NaT,NaT,0 days 00:00:12.773000,Finished,10.0,57.0
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,6.0,6,13.0,NaT,NaT,NaT,0 days 00:00:17.413000,Finished,8.0,57.0
27,27,N HULKENBERG,HUL,hulkenberg,Kick Sauber,52E252,sauber,Nico,Hulkenberg,Nico Hulkenberg,...,7.0,7,17.0,NaT,NaT,NaT,0 days 00:00:18.423000,Finished,6.0,57.0
16,16,C LECLERC,LEC,leclerc,Ferrari,E80020,ferrari,Charles,Leclerc,Charles Leclerc,...,8.0,8,7.0,NaT,NaT,NaT,0 days 00:00:19.826000,Finished,4.0,57.0
81,81,O PIASTRI,PIA,piastri,McLaren,FF8000,mclaren,Oscar,Piastri,Oscar Piastri,...,9.0,9,2.0,NaT,NaT,NaT,0 days 00:00:20.448000,Finished,2.0,57.0
44,44,L HAMILTON,HAM,hamilton,Ferrari,E80020,ferrari,Lewis,Hamilton,Lewis Hamilton,...,10.0,10,8.0,NaT,NaT,NaT,0 days 00:00:22.473000,Finished,1.0,57.0
10,10,P GASLY,GAS,gasly,Alpine,0093CC,alpine,Pierre,Gasly,Pierre Gasly,...,11.0,11,9.0,NaT,NaT,NaT,0 days 00:00:26.502000,Finished,0.0,57.0
22,22,Y TSUNODA,TSU,tsunoda,Racing Bulls,6692FF,rb,Yuki,Tsunoda,Yuki Tsunoda,...,12.0,12,5.0,NaT,NaT,NaT,0 days 00:00:29.884000,Finished,0.0,57.0
31,31,E OCON,OCO,ocon,Haas F1 Team,B6BABD,haas,Esteban,Ocon,Esteban Ocon,...,13.0,13,19.0,NaT,NaT,NaT,0 days 00:00:33.161000,Finished,0.0,57.0
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,B6BABD,haas,Oliver,Bearman,Oliver Bearman,...,14.0,14,20.0,NaT,NaT,NaT,0 days 00:00:40.351000,Finished,0.0,57.0
30,30,L LAWSON,LAW,lawson,Red Bull Racing,3671C6,red_bull,Liam,Lawson,Liam Lawson,...,15.0,R,18.0,NaT,NaT,NaT,NaT,Retired,0.0,46.0
5,5,G BORTOLETO,BOR,bortoleto,Kick Sauber,52E252,sauber,Gabriel,Bortoleto,Gabriel Bortoleto,...,16.0,R,15.0,NaT,NaT,NaT,NaT,Retired,0.0,45.0
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,17.0,R,12.0,NaT,NaT,NaT,NaT,Retired,0.0,32.0
55,55,C SAINZ,SAI,sainz,Williams,64C4FF,williams,Carlos,Sainz,Carlos Sainz,...,18.0,R,10.0,NaT,NaT,NaT,NaT,Retired,0.0,0.0
7,7,J DOOHAN,DOO,doohan,Alpine,0093CC,alpine,Jack,Doohan,Jack Doohan,...,19.0,R,14.0,NaT,NaT,NaT,NaT,Retired,0.0,0.0
6,6,I HADJAR,HAD,hadjar,Racing Bulls,6692FF,rb,Isack,Hadjar,Isack Hadjar,...,20.0,R,11.0,NaT,NaT,NaT,NaT,Retired,0.0,0.0

In [20]:
session.results.columns

Index(['DriverNumber', 'BroadcastName', 'Abbreviation', 'DriverId', 'TeamName',
       'TeamColor', 'TeamId', 'FirstName', 'LastName', 'FullName',
       'HeadshotUrl', 'CountryCode', 'Position', 'ClassifiedPosition',
       'GridPosition', 'Q1', 'Q2', 'Q3', 'Time', 'Status', 'Points', 'Laps'],
      dtype='object')

In [27]:
# .loc[row_selection, column_selection]

session.results.iloc[0:10]
session.results.iloc[0:10].loc[:, ["Abbreviation", "TeamName"]]

   Abbreviation         TeamName
4           NOR          McLaren
1           VER  Red Bull Racing
63          RUS         Mercedes
12          ANT         Mercedes
23          ALB         Williams
18          STR     Aston Martin
27          HUL      Kick Sauber
16          LEC          Ferrari
81          PIA          McLaren
44          HAM          Ferrari

In [28]:
session.laps

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 01:13:00.002000,VER,1,0 days 00:01:59.392000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:20.705000,...,True,Red Bull Racing,0 days 01:11:00.355000,2025-03-16 04:18:22.974,124,2.0,False,,False,False
1,0 days 01:15:49.358000,VER,1,NaT,2.0,1.0,NaT,0 days 01:15:38.205000,0 days 00:00:58.141000,0 days 00:00:37.976000,...,True,Red Bull Racing,0 days 01:13:00.002000,2025-03-16 04:20:22.621,4,2.0,False,,False,False
2,0 days 01:18:31.526000,VER,1,NaT,3.0,2.0,0 days 01:15:51.658000,0 days 01:18:20.223000,0 days 00:00:56.230000,0 days 00:00:33.683000,...,False,Red Bull Racing,0 days 01:15:49.358000,2025-03-16 04:23:11.977,4,2.0,False,,False,False
3,0 days 01:21:07.226000,VER,1,NaT,4.0,3.0,0 days 01:18:34.029000,0 days 01:20:56.543000,0 days 00:00:54.351000,0 days 00:00:32.712000,...,False,Red Bull Racing,0 days 01:18:31.526000,2025-03-16 04:25:54.145,4,2.0,False,,False,False
4,0 days 01:23:30.835000,VER,1,0 days 00:02:23.609000,5.0,4.0,0 days 01:21:09.534000,NaT,0 days 00:00:53.513000,0 days 00:00:32.627000,...,False,Red Bull Racing,0 days 01:21:07.226000,2025-03-16 04:28:29.845,4,2.0,False,,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922,0 days 02:47:44.697000,BEA,87,0 days 00:01:31.366000,53.0,6.0,NaT,NaT,0 days 00:00:31.993000,0 days 00:00:19.286000,...,True,Haas F1 Team,0 days 02:46:13.331000,2025-03-16 05:53:35.950,1,14.0,False,,False,True
923,0 days 02:49:15.187000,BEA,87,0 days 00:01:30.490000,54.0,6.0,NaT,NaT,0 days 00:00:31.429000,0 days 00:00:19.147000,...,True,Haas F1 Team,0 days 02:47:44.697000,2025-03-16 05:55:07.316,1,14.0,False,,False,True
924,0 days 02:50:46.471000,BEA,87,0 days 00:01:31.284000,55.0,6.0,NaT,NaT,0 days 00:00:31.538000,0 days 00:00:19.483000,...,True,Haas F1 Team,0 days 02:49:15.187000,2025-03-16 05:56:37.806,1,14.0,False,,False,True
925,0 days 02:52:16.697000,BEA,87,0 days 00:01:30.226000,56.0,6.0,NaT,NaT,0 days 00:00:31.349000,0 days 00:00:19.207000,...,True,Haas F1 Team,0 days 02:50:46.471000,2025-03-16 05:58:09.090,1,14.0,False,,False,True
926,0 days 02:53:47.250000,BEA,87,0 days 00:01:30.553000,57.0,6.0,NaT,NaT,0 days 00:00:31.384000,0 days 00:00:19.175000,...,True,Haas F1 Team,0 days 02:52:16.697000,2025-03-16 05:59:39.316,1,14.0,False,,False,True

In [29]:
fastest_lap = session.laps.pick_fastest()
fastest_lap

Time                      0 days 02:28:03.586000
Driver                                       NOR
DriverNumber                                   4
LapTime                   0 days 00:01:22.167000
LapNumber                                   43.0
Stint                                        5.0
PitOutTime                                   NaT
PitInTime                                    NaT
Sector1Time               0 days 00:00:28.553000
Sector2Time               0 days 00:00:18.537000
Sector3Time               0 days 00:00:35.077000
Sector1SessionTime        0 days 02:27:10.030000
Sector2SessionTime        0 days 02:27:28.567000
Sector3SessionTime        0 days 02:28:03.644000
SpeedI1                                    271.0
SpeedI2                                    290.0
SpeedFL                                    292.0
SpeedST                                    300.0
IsPersonalBest                              True
Compound                                    HARD
TyreLife                                    10.0
FreshTyre                                  False
Team                                     McLaren
LapStartTime              0 days 02:26:41.419000
LapStartDate          2025-03-16 05:34:04.038000
TrackStatus                                    1
Position                                     1.0
Deleted                                    False
DeletedReason
FastF1Generated                            False
IsAccurate                                  True
Name: 635, dtype: object